### ISSUE TITLE
Could not find org.kordamp:markdown-gradle-plugin:2.2.0

### ISSUE THREAD

**Issue by al-t** [kordamp/markdown-gradle-plugin#29]
Gradle could not find dependency

```
Could not find org.kordamp:markdown-gradle-plugin:2.2.0.
Searched in the following locations:
  - http://dl.bintray.com/content/kordamp/kordamp/org/kordamp/markdown-gradle-plugin/2.2.0/markdown-gradle-plugin-2.2.0.pom
  - https://maven.fabric.io/public/org/kordamp/markdown-gradle-plugin/2.2.0/markdown-gradle-plugin-2.2.0.pom
  - https://dl.google.com/dl/android/maven2/org/kordamp/markdown-gradle-plugin/2.2.0/markdown-gradle-plugin-2.2.0.pom
  - https://jcenter.bintray.com/org/kordamp/markdown-gradle-plugin/2.2.0/markdown-gradle-plugin-2.2.0.pom
  - https://plugins.gradle.org/m2/org/kordamp/markdown-gradle-plugin/2.2.0/markdown-gradle-plugin-2.2.0.pom
  - https://repo.maven.apache.org/maven2/org/kordamp/markdown-gradle-plugin/2.2.0/markdown-gradle-plugin-2.2.0.pom
```

The same happens with any version >= 2.0.0 (with 1.2.0 it works fine).

**Comment by aalmiray** [comment]
This is odd

    $ curl -i https://plugins.gradle.org/m2/org/kordamp/markdown-gradle-plugin/2.2.0/markdown-gradle-plugin-2.2.0.pom
    HTTP/1.1 303 See Other
    Date: Tue, 02 Jun 2020 12:04:29 GMT
    Content-Length: 0
    Connection: keep-alive
    Set-Cookie: __cfduid=d08a1ba32f295ec46f128d22f3f3142ed1591099468; expires=Thu, 02-Jul-20 12:04:28 GMT; path=/; domain=.gradle.org; HttpOnly; SameSite=Lax; Secure
    Location: https://jcenter.bintray.com/org/kordamp/markdown-gradle-plugin/2.2.0/markdown-gradle-plugin-2.2.0.pom
    Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
    X-Frame-Options: DENY
    X-Xss-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline' data: fonts.googleapis.com; script-src 'self' ajax.googleapis.com stackpath.bootstrapcdn.com cdnjs.cloudflare.com cdn.pardot.com pi.pardot.com z8s4n2jmrsl0.statuspage.io go.gradle.com fast.wistia.com www.google-analytics.com 'sha256-3qctdUZX/6QPVNn4hg55oarXzLBDDCkQ6AaG8ehXgDg=' 'sha256-FaUMgnLu84fq7a00IOk9lIEfB5qLYaTff4c3Y59qX/0=' 'sha256-ZqVyBZIOnOs0ufJvaehuhjzSkrVKIH4DFy95DJ8pDxw=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' 'sha256-bzgPbiBbhlwatKiESkSqGJr5wldMGBU+GAbfeWwMqBM=' 'sha256-cThjNwQ0AS+/Z2uD76101UnXGOH65pSGKTbFESeaGzE='; font-src 'self' data: fonts.gstatic.com assets.gradle.com; img-src 'self' unpkg.com www.gravatar.com *.githubusercontent.com; frame-src 'self' z8s4n2jmrsl0.statuspage.io
    X-Permitted-Cross-Domain-Policies: master-only
    Via: 1.1 vegur
    CF-Cache-Status: DYNAMIC
    cf-request-id: 031684444e0000cc5a4192d200000001
    Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
    Strict-Transport-Security: max-age=2592000; includeSubDomains
    Server: cloudflare
    CF-RAY: 59d109807802cc5a-ZRH

Shows a redirect to JCenter, but the plugin should not be there at all. Compare with another plugin

$ curl -i https://plugins.gradle.org/m2/org/kordamp/gradle/base-gradle-plugin/0.36.0/base-gradle-plugin-0.36.0.pom
HTTP/1.1 303 See Other
Date: Tue, 02 Jun 2020 12:05:44 GMT
Content-Length: 0
Connection: keep-alive
Set-Cookie: __cfduid=d2a31f535f4b903b776712c41ded7483a1591099544; expires=Thu, 02-Jul-20 12:05:44 GMT; path=/; domain=.gradle.org; HttpOnly; SameSite=Lax; Secure
Location: https://plugins-artifacts.gradle.org/org.kordamp.gradle/base-gradle-plugin/0.36.0/c8b901f589a9890b0d08d79349371621e00a04cbc4bf42b06d3502a6c020944a/base-gradle-plugin-0.36.0.pom
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline' data: fonts.googleapis.com; script-src 'self' ajax.googleapis.com stackpath.bootstrapcdn.com cdnjs.cloudflare.com cdn.pardot.com pi.pardot.com z8s4n2jmrsl0.statuspage.io go.gradle.com fast.wistia.com www.google-analytics.com 'sha256-3qctdUZX/6QPVNn4hg55oarXzLBDDCkQ6AaG8ehXgDg=' 'sha256-FaUMgnLu84fq7a00IOk9lIEfB5qLYaTff4c3Y59qX/0=' 'sha256-ZqVyBZIOnOs0ufJvaehuhjzSkrVKIH4DFy95DJ8pDxw=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' 'sha256-bzgPbiBbhlwatKiESkSqGJr5wldMGBU+GAbfeWwMqBM=' 'sha256-cThjNwQ0AS+/Z2uD76101UnXGOH65pSGKTbFESeaGzE='; font-src 'self' data: fonts.gstatic.com assets.gradle.com; img-src 'self' unpkg.com www.gravatar.com *.githubusercontent.com; frame-src 'self' z8s4n2jmrsl0.statuspage.io
X-Permitted-Cross-Domain-Policies: master-only
Via: 1.1 vegur
CF-Cache-Status: DYNAMIC
cf-request-id: 0316856ab80000cc464b1b7200000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Strict-Transport-Security: max-age=2592000; includeSubDomains
Server: cloudflare
CF-RAY: 59d10b578948cc46-ZRH

Which is correctly redirected. Applying the plugin using the `plugins` block yields

    $ cat build.gradle 
    plugins {
      id "org.kordamp.gradle.markdown" version "2.2.0"
    }
    
    $ gm tasks --all
    Using gradle at '/Users/aalmiray/.sdkman/candidates/gradle/current/bin/gradle' to run buildFile '/tmp/build.gradle':
    
    > Task :tasks
    
    ------------------------------------------------------------
    Tasks runnable from root project
    ------------------------------------------------------------
    
    Build Setup tasks
    -----------------
    init - Initializes a new Gradle build.
    wrapper - Generates Gradle wrapper files.
    
    Documentation tasks
    -------------------
    htmlToMarkdown - Converts HTML into Markdown
    markdownToHtml - Converts Markdown sources into HTML
    
    Help tasks
    ----------
    buildEnvironment - Displays all buildscript dependencies declared in root project 'tmp'.
    components - Displays the components produced by root project 'tmp'. [incubating]
    dependencies - Displays all dependencies declared in root project 'tmp'.
    dependencyInsight - Displays the insight into a specific dependency in root project 'tmp'.
    dependentComponents - Displays the dependent components of components in root project 'tmp'. [incubating]
    help - Displays a help message.
    model - Displays the configuration model of root project 'tmp'. [incubating]
    outgoingVariants - Displays the outgoing variants of root project 'tmp'.
    projects - Displays the sub-projects of root project 'tmp'.
    properties - Displays the properties of root project 'tmp'.
    tasks - Displays the tasks runnable from root project 'tmp'.
    
    Other tasks
    -----------
    prepareKotlinBuildScriptModel
    
    BUILD SUCCESSFUL in 516ms
    1 actionable task: 1 executed

Same if applying the plugin using `buildscript`

    $ cat build.gradle 
    buildscript {
      repositories {
        gradlePluginPortal()
      }
      dependencies {
        classpath "org.kordamp.gradle:markdown-gradle-plugin:2.2.0"
      }
    }
    
    apply plugin: "org.kordamp.gradle.markdown"

Are you consuming the plugin in a different way?

**Comment by laurentyhuel** [comment]
I think I have same issue. I use your plugin in my own gradle plugin, as this : 
**gradle.properties**
```
kordampMarkdown = 2.2.0
```
**build.gradle**
```
dependencies {
    implementation "org.kordamp.gradle.markdown:org.kordamp.gradle.markdown.gradle.plugin:$kordampMarkdown"
}
```
**GradleCore.groovy**
import org.kordamp.gradle.plugin.markdown.MarkdownPlugin
class GradleCore implements Plugin<Project> {
    @Override void apply(Project project) {
        project.getPluginManager().apply(MarkdownPlugin)
    }
}

**Comment by aalmiray** [comment]
The plugin is listed at the Gradle Plugin Portal. You must make sure that the `gradlePluginPortal()` repository is configured in the build.

**Comment by a4z** [comment]
I have the same problem
```
 Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.kordamp:markdown-gradle-plugin:2.2.0.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/kordamp/markdown-gradle-plugin/2.2.0/markdown-gradle-plugin-2.2.0.pom
       - https://plugins.gradle.org/m2/org/kordamp/markdown-gradle-plugin/2.2.0/markdown-gradle-plugin-2.2.0.pom
       - http://dl.bintray.com/content/kordamp/kordamp/org/kordamp/markdown-gradle-plugin/2.2.0/markdown-gradle-plugin-2.2.0.pom
       - https://dl.google.com/dl/android/maven2/org/kordamp/markdown-gradle-plugin/2.2.0/markdown-gradle-plugin-2.2.0.pom
     Required by:
         project :
```

**Comment by aalmiray** [comment]
I can see why. the README listed the wrong coordinates when applying the plugin using the old `buildscript` block. The coordinates *should* be `org.kordamp.gradle:markdown-gradle-plugin:2.2.0`.

**Comment by a4z** [comment]
yes, now it works :-) 
Thank you very much for the fast reply Andreas! This saves my evening :-)

**Comment by aalmiray** [comment]
I updated the README to reflect the coordinates change. I must confess I was puzzled by this thing not working until I really paid attention to what was written on the README.
